apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: db_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: prajyotparab31904/employee-db:v1
          name: database
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: database-claim
      restartPolicy: Always
      volumes:
        - name: database-claim
          persistentVolumeClaim:
            claimName: database-claim
status: {}
