apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: database-claim
  name: database-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
