apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-service
  name: employee-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: employee-service
status:
  loadBalancer: {}
