apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: employee-service-claim
  name: employee-service-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
